name: Build

on:
  push:
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  wheels_aarch64:
    name: Build Linux wheels on aarch64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      name: Install Python
      with:
        python-version: '3.10'
    - uses: docker/setup-qemu-action@v2
      name: Set up QEMU
      with:
        platforms: arm64
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.2
      env:
        CIBW_ARCHS_LINUX: aarch64
        CIBW_TEST_REQUIRES: pytest numpy
        CIBW_TEST_COMMAND: "pytest -v {project}/tests"
        CIBW_BEFORE_ALL_LINUX: "pip install cmake; bash {project}/ci/install_libspatialindex.bash"
    - uses: actions/upload-artifact@v3
      with:
        name: aarch64-whl
        path: wheelhouse/*.whl
